<!DOCTYPE html>
<html lang="ua">
    <head>
        <meta charset="utf-8">
        <title>Висказати свою думку.</title>
    </head>
    <body>
        <header>
            <h1>Висказати свою думку.</h1>
        </header>
        <nav>
            <a href="" title="">Усі думки</a>
            <a href="" title="" class="selected">Висказати свою думку.</a>
        </nav>
        <article>
            <?php echo $this->main ?>
        </article>
        <footer>
            ВО Батьківщина
        </footer>
    </body>
</html>